version: '3.8'

services:

  mysqldb:
    container_name: mysql8
    cap_add:
      - SYS_NICE
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: config_audit
       MYSQL_USER: sandbox_user
       MYSQL_PASSWORD: passpass
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    user: mysql
    volumes:
      - ./my-datavolume:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  config-audit:
    image: config-audit-v1
    container_name: config-audit
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:secret@mysql8:3306/config_audit
      SOLACE_CLOUD_TOKEN: ${SOLACE_CLOUD_TOKEN}
      SOLACE_URL: https://api.solace.cloud
